#!/bin/bash
# Hooker run.sh — bridge between project settings.json and hooker plugin.
# Generated by /hooker:recipe install. Finds the hooker plugin in known
# locations and delegates to inject.sh.
#
# Usage in .claude/settings.json:
#   { "command": ".claude/hooker/run.sh .claude/hooker/recipe-name/PostToolUse" }
#
# The argument is the path to the recipe hook:
#   dirname  → recipe directory (contains match scripts, templates, messages)
#   basename → hook event name (PostToolUse, Stop, SessionStart, etc.)

set -euo pipefail

# Override: set HOOKER_ROOT env var or edit this line to skip auto-detection.
# Useful if plugin cache structure changes in a future Claude Code version.
HOOKER_ROOT_OVERRIDE=""

find_hooker() {
    # 0. Explicit override (env var or hardcoded above)
    local OVERRIDE="${HOOKER_ROOT:-${HOOKER_ROOT_OVERRIDE}}"
    if [ -n "$OVERRIDE" ] && [ -f "${OVERRIDE}/scripts/inject.sh" ]; then
        echo "$OVERRIDE"
        return
    fi

    # 1. CLAUDE_PLUGIN_ROOT already set (running inside plugin context)
    if [ -n "${CLAUDE_PLUGIN_ROOT:-}" ] && [ -f "${CLAUDE_PLUGIN_ROOT}/scripts/inject.sh" ]; then
        echo "$CLAUDE_PLUGIN_ROOT"
        return
    fi

    # 2. Plugin cache — find latest installed version
    #    Path structure: ~/.claude/plugins/cache/{marketplace-name}/{plugin-name}/{version}/
    #    WARNING: this path structure is not guaranteed by Anthropic.
    #    If it changes, set HOOKER_ROOT env var or edit HOOKER_ROOT_OVERRIDE above.
    local CACHE_DIR="${HOME}/.claude/plugins/cache/hooker-marketplace/hooker"
    if [ -d "$CACHE_DIR" ]; then
        local LATEST
        LATEST=$(ls -v "$CACHE_DIR" 2>/dev/null | tail -1)
        if [ -n "$LATEST" ] && [ -f "${CACHE_DIR}/${LATEST}/scripts/inject.sh" ]; then
            echo "${CACHE_DIR}/${LATEST}"
            return
        fi
    fi

    # 3. Marketplace source
    local MP="${HOME}/.claude/plugins/marketplaces/hooker-marketplace"
    if [ -f "${MP}/scripts/inject.sh" ]; then
        echo "$MP"
        return
    fi

    # 4. Brute-force: find inject.sh anywhere in plugin cache
    local FOUND
    FOUND=$(find "${HOME}/.claude/plugins" -path "*/hooker/scripts/inject.sh" -type f 2>/dev/null | head -1)
    if [ -n "$FOUND" ]; then
        echo "$(dirname "$(dirname "$FOUND")")"
        return
    fi

    return 1
}

HOOKER_ROOT=$(find_hooker) || {
    echo "Hooker plugin not found" >&2
    exit 1
}

export CLAUDE_PLUGIN_ROOT="$HOOKER_ROOT"
exec "$HOOKER_ROOT/scripts/inject.sh" --recipe "$1"
