#!/bin/bash
# Hooker run.sh — bridge between project settings.json and hooker plugin.
# Generated by /hooker:recipe install. Finds the hooker plugin in known
# locations and delegates to inject.sh.
#
# Usage in .claude/settings.json:
#   { "command": ".claude/hooker/run.sh .claude/hooker/recipe-name/PostToolUse" }
#
# The argument is the path to the recipe hook:
#   dirname  → recipe directory (contains match scripts, templates, messages)
#   basename → hook event name (PostToolUse, Stop, SessionStart, etc.)

set -euo pipefail

find_hooker() {
    # 1. CLAUDE_PLUGIN_ROOT already set (running inside plugin context)
    if [ -n "${CLAUDE_PLUGIN_ROOT:-}" ] && [ -f "${CLAUDE_PLUGIN_ROOT}/scripts/inject.sh" ]; then
        echo "$CLAUDE_PLUGIN_ROOT"
        return
    fi

    # 2. Plugin cache — find latest installed version
    local CACHE_DIR="${HOME}/.claude/plugins/cache/hooker-marketplace/hooker"
    if [ -d "$CACHE_DIR" ]; then
        local LATEST
        LATEST=$(ls -v "$CACHE_DIR" 2>/dev/null | tail -1)
        if [ -n "$LATEST" ] && [ -f "${CACHE_DIR}/${LATEST}/scripts/inject.sh" ]; then
            echo "${CACHE_DIR}/${LATEST}"
            return
        fi
    fi

    # 3. Marketplace source
    local MP="${HOME}/.claude/plugins/marketplaces/hooker-marketplace"
    if [ -f "${MP}/scripts/inject.sh" ]; then
        echo "$MP"
        return
    fi

    return 1
}

HOOKER_ROOT=$(find_hooker) || {
    echo "Hooker plugin not found" >&2
    exit 1
}

export CLAUDE_PLUGIN_ROOT="$HOOKER_ROOT"
exec "$HOOKER_ROOT/scripts/inject.sh" --recipe "$1"
