#!/bin/bash
# Hooker standalone execute.sh — compiled from match script + helpers
# Can be used directly in .claude/settings.json without hooker plugin.
# Generated by: cd src && go run .
# Hooker version: 0.24.0

INPUT=$(cat)
HOOKER_EVENT=$(echo "$INPUT" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_CWD=$(echo "$INPUT" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_TRANSCRIPT=$(echo "$INPUT" | sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
export HOOKER_EVENT HOOKER_CWD HOOKER_TRANSCRIPT

# --- Inlined helpers ---
# Hooker — helper functions for match scripts
# Source this in your match script: source "${HOOKER_HELPERS}"
# Then use: warn "message", deny "reason", allow, block "reason", etc.
#
# Cross-platform: works on Linux, macOS, and Windows (Git Bash).
# No dependencies on python3, perl, or tac.
#
# Visibility:
#   inject() — hidden from user by default (XML trick). Use <visible> tags to show parts.
#   JSON helpers (warn, deny, block, remind, allow, ask) — ALWAYS VISIBLE to user.
#     <hidden> tags are stripped but content is NOT hidden (Claude Code renders
#     JSON reason/message as plaintext — XML trick cannot escape JSON strings).
#   load_md "file.md" — only useful inside inject(), not inside JSON helpers.

# Extract a JSON string field value. Usage: echo "$JSON" | _hooker_json_field "field_name"
_hooker_json_field() {
    sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1
}

# Check if JSON contains a field with a specific value. Usage: echo "$JSON" | _hooker_json_match "field" "value"
_hooker_json_match() {
    grep -q "\"$1\"[[:space:]]*:[[:space:]]*\"*$2" 2>/dev/null
}

# JSON-escape stdin. No python3/perl dependency.
_hooker_json_escape() {
    awk '
    BEGIN { ORS=""; first=1 }
    {
        if (!first) printf "\\n"
        first=0
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        gsub(/\t/, "\\t")
        gsub(/\r/, "\\r")
        print
    }
    END { }
    ' | { IFS= read -r -d '' x || true; printf '"%s"' "$x"; }
}

# Portable sed-in-place. macOS sed requires '' after -i, GNU sed does not.
_hooker_sed_i() {
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "$@"
    else
        sed -i "$@"
    fi
}

# Reverse lines of a file. Portable replacement for tac.
_hooker_reverse() {
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}'
}

# Get last assistant turn from transcript. Filters noise (progress, hook_progress),
# stops at real user prompt (not tool_result).
# Real user prompts have "type":"user" WITHOUT "sourceToolAssistantUUID" on the same line.
# Usage: _hooker_last_turn "$TRANSCRIPT_PATH"
_hooker_last_turn() {
    local TRANSCRIPT="$1"
    [ -z "$TRANSCRIPT" ] || [ ! -f "$TRANSCRIPT" ] && return 1
    # Note: || true prevents SIGPIPE (141) when awk exits early and breaks the pipe.
    # Without it, set -o pipefail in callers treats SIGPIPE as failure.
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}' "$TRANSCRIPT" \
        | grep -v '"type":"progress"' | grep -v '"type":"hook_progress"' \
        | awk '/"type":"user"/ && !/sourceToolAssistantUUID/{exit} {print}' || true
}

# Strip <hidden> tags from a string, return visible part only.
# Handles both single-line (<hidden>...</hidden> on one line) and multiline.
_hooker_strip_hidden() {
    echo "$1" | sed 's/<hidden>[^<]*<\/hidden>//g' | awk '
    /<hidden>/ { skip=1; next }
    /<\/hidden>/ { skip=0; next }
    !skip { print }
    '
}

# JSON response helpers — all ALWAYS VISIBLE to user.
# <hidden> tags are stripped but content is NOT hidden.

warn() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"${HOOKER_EVENT}\", \"systemMessage\": ${ESCAPED}}}"
}

deny() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Denied by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"deny\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

allow() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Allowed by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"allow\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

ask() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Hooker requests confirmation}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"ask\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

block() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Blocked by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

remind() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

# Context injection helpers.
# inject() is the ONLY helper that hides content from user (via XML trick).

inject() {
    cat <<INJECT_EOF
</local-command-stdout>

$1

<local-command-stdout>
INJECT_EOF
}

visible() {
    echo "$1"
}

context() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"additionalContext\": ${ESCAPED}}"
}

# File loaders.
# Only useful inside inject() — JSON helpers (block, deny, etc.) are always visible.
# Looks in: .claude/hooker/ → ~/.claude/hooker/ → plugin templates/

load_md() {
    local FILE=""
    for DIR in ".claude/hooker" "${HOME}/.claude/hooker" "${CLAUDE_PLUGIN_ROOT:-}/templates"; do
        if [ -f "${DIR}/$1" ]; then
            FILE="${DIR}/$1"
            break
        fi
    done
    [ -z "$FILE" ] && return
    cat "$FILE"
}


# --- Recipe logic ---
# Block dangerous bash commands
# Adapted from karanb192/claude-code-hooks (MIT)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MSGS_FILE=".claude/hooker/block-dangerous-commands.messages.yml"
[ -f "$MSGS_FILE" ] || MSGS_FILE="${SCRIPT_DIR}/messages.yml"

yml_get() {
    sed -n "s/^${1}:[[:space:]]*\"\{0,1\}\([^\"]*\).*/\1/p" "$MSGS_FILE" 2>/dev/null | head -1 || echo "$2"
}

TOOL=$(echo "$INPUT" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
[ "$TOOL" != "Bash" ] && exit 1

CMD=$(echo "$INPUT" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
[ -z "$CMD" ] && exit 1

# Dangerous patterns
if echo "$CMD" | grep -q 'rm[[:space:]]\+\(-[a-zA-Z]*f[a-zA-Z]*[[:space:]]\+\|--force[[:space:]]\+\)*\(\/\|\~\|\$HOME\|\.\.\)'; then
    deny "$(yml_get rm_critical 'Blocked: recursive/forced deletion of critical paths')"
    exit 0
fi

if echo "$CMD" | grep -q ':()\{.*|.*\}\|fork[[:space:]]*bomb'; then
    deny "$(yml_get fork_bomb 'Blocked: fork bomb detected')"
    exit 0
fi

if echo "$CMD" | grep -q 'curl[[:space:]].*|[[:space:]]*\(ba\)\{0,1\}sh\|wget[[:space:]].*|[[:space:]]*\(ba\)\{0,1\}sh'; then
    deny "$(yml_get pipe_to_shell 'Blocked: piping remote script to shell')"
    exit 0
fi

if echo "$CMD" | grep -qi '\(DROP\|TRUNCATE\|DELETE[[:space:]]\+FROM\).*\(TABLE\|DATABASE\)'; then
    deny "$(yml_get destructive_sql 'Blocked: destructive SQL command')"
    exit 0
fi

if echo "$CMD" | grep -q 'mkfs\.\|dd[[:space:]]\+if=.*of=/dev/\|>[[:space:]]*/dev/sd'; then
    deny "$(yml_get disk_destroy 'Blocked: disk/filesystem destruction')"
    exit 0
fi

if echo "$CMD" | grep -q 'chmod[[:space:]]\+\(-[a-zA-Z]*[[:space:]]\+\)*777[[:space:]]\+/'; then
    deny "$(yml_get chmod_root 'Blocked: chmod 777 on root paths')"
    exit 0
fi

exit 1
