#!/bin/bash
# Hooker run.sh — bridge between project settings.json and hooker plugin.
# Generated by /hooker:recipe install. Finds the hooker plugin and delegates
# to inject.sh.
#
# Usage in .claude/settings.json:
#   { "command": ".claude/hooker/run.sh .claude/hooker/recipe-name/PostToolUse" }
#
# The argument is the path to the recipe hook:
#   dirname  → recipe directory (contains match scripts, templates, messages)
#   basename → hook event name (PostToolUse, Stop, SessionStart, etc.)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Load config from hooker.env (generated by /hooker:recipe install)
# HOOKER_CACHE_DIR — versioned cache parent (auto-picks latest version)
# HOOKER_ROOT      — exact plugin path (skips version detection)
[ -f "${SCRIPT_DIR}/hooker.env" ] && . "${SCRIPT_DIR}/hooker.env"

# Resolve latest version from a cache dir containing version subdirectories
resolve_latest() {
    local DIR="$1"
    [ -d "$DIR" ] || return 1
    local LATEST
    LATEST=$(ls -v "$DIR" 2>/dev/null | tail -1)
    [ -n "$LATEST" ] && [ -f "${DIR}/${LATEST}/scripts/inject.sh" ] && echo "${DIR}/${LATEST}" && return
    return 1
}

find_hooker() {
    # 0. Exact path from hooker.env or environment
    if [ -n "${HOOKER_ROOT:-}" ] && [ -f "${HOOKER_ROOT}/scripts/inject.sh" ]; then
        echo "$HOOKER_ROOT"
        return
    fi

    # 1. Cache dir from hooker.env — auto-picks latest version
    if [ -n "${HOOKER_CACHE_DIR:-}" ]; then
        resolve_latest "$HOOKER_CACHE_DIR" && return
    fi

    # 2. CLAUDE_PLUGIN_ROOT (set when running inside plugin context)
    if [ -n "${CLAUDE_PLUGIN_ROOT:-}" ] && [ -f "${CLAUDE_PLUGIN_ROOT}/scripts/inject.sh" ]; then
        echo "$CLAUDE_PLUGIN_ROOT"
        return
    fi

    # 3. Default cache path — latest version
    #    WARNING: path structure not guaranteed by Anthropic.
    #    If broken, update .claude/hooker/hooker.env
    resolve_latest "${HOME}/.claude/plugins/cache/hooker-marketplace/hooker" && return
    resolve_latest "${HOME}/.claude/plugins/cache/treetank-marketplace/hooker" && return

    # 4. Marketplace source
    local MP
    for MP in "${HOME}/.claude/plugins/marketplaces/hooker-marketplace" "${HOME}/.claude/plugins/marketplaces/treetank-marketplace"; do
        if [ -f "${MP}/scripts/inject.sh" ]; then
            echo "$MP"
            return
        fi
    done

    # 5. Brute-force: find inject.sh anywhere in plugin dirs
    local FOUND
    FOUND=$(find "${HOME}/.claude/plugins" -path "*/hooker/scripts/inject.sh" -type f 2>/dev/null | head -1)
    if [ -n "$FOUND" ]; then
        echo "$(dirname "$(dirname "$FOUND")")"
        return
    fi

    return 1
}

HOOKER_ROOT=$(find_hooker) || {
    echo "Hooker plugin not found" >&2
    exit 1
}

export CLAUDE_PLUGIN_ROOT="$HOOKER_ROOT"
exec "$HOOKER_ROOT/scripts/inject.sh" --recipe "$1"
