#!/bin/bash
# Hooker standalone execute.sh — compiled from match script + helpers
# Can be used directly in .claude/settings.json without hooker plugin.
# Generated by: cd src && go run .
# Hooker version: 0.19.0

INPUT=$(cat)
HOOKER_EVENT=$(echo "$INPUT" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_CWD=$(echo "$INPUT" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_TRANSCRIPT=$(echo "$INPUT" | sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
export HOOKER_EVENT HOOKER_CWD HOOKER_TRANSCRIPT

# --- Inlined helpers ---
# Hooker — helper functions for match scripts
# Source this in your match script: source "${HOOKER_HELPERS}"
# Then use: warn "message", deny "reason", allow, block "reason", etc.
#
# Cross-platform: works on Linux, macOS, and Windows (Git Bash).
# No dependencies on python3, perl, or tac.
#
# Visibility:
#   inject() — hidden from user by default (XML trick). Use <visible> tags to show parts.
#   JSON helpers (warn, deny, block, remind, allow, ask) — ALWAYS VISIBLE to user.
#     <hidden> tags are stripped but content is NOT hidden (Claude Code renders
#     JSON reason/message as plaintext — XML trick cannot escape JSON strings).
#   load_md "file.md" — only useful inside inject(), not inside JSON helpers.

# Extract a JSON string field value. Usage: echo "$JSON" | _hooker_json_field "field_name"
_hooker_json_field() {
    sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1
}

# Check if JSON contains a field with a specific value. Usage: echo "$JSON" | _hooker_json_match "field" "value"
_hooker_json_match() {
    grep -q "\"$1\"[[:space:]]*:[[:space:]]*\"*$2" 2>/dev/null
}

# JSON-escape stdin. No python3/perl dependency.
_hooker_json_escape() {
    awk '
    BEGIN { ORS=""; first=1 }
    {
        if (!first) printf "\\n"
        first=0
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        gsub(/\t/, "\\t")
        gsub(/\r/, "\\r")
        print
    }
    END { }
    ' | { IFS= read -r -d '' x || true; printf '"%s"' "$x"; }
}

# Portable sed-in-place. macOS sed requires '' after -i, GNU sed does not.
_hooker_sed_i() {
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "$@"
    else
        sed -i "$@"
    fi
}

# Reverse lines of a file. Portable replacement for tac.
_hooker_reverse() {
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}'
}

# Get last assistant turn from transcript. Filters noise (progress, hook_progress),
# stops at real user prompt (not tool_result).
# Real user prompts have "type":"user" WITHOUT "sourceToolAssistantUUID" on the same line.
# Usage: _hooker_last_turn "$TRANSCRIPT_PATH"
_hooker_last_turn() {
    local TRANSCRIPT="$1"
    [ -z "$TRANSCRIPT" ] || [ ! -f "$TRANSCRIPT" ] && return 1
    # Note: || true prevents SIGPIPE (141) when awk exits early and breaks the pipe.
    # Without it, set -o pipefail in callers treats SIGPIPE as failure.
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}' "$TRANSCRIPT" \
        | grep -v '"type":"progress"' | grep -v '"type":"hook_progress"' \
        | awk '/"type":"user"/ && !/sourceToolAssistantUUID/{exit} {print}' || true
}

# Strip <hidden> tags from a string, return visible part only.
# Handles both single-line (<hidden>...</hidden> on one line) and multiline.
_hooker_strip_hidden() {
    echo "$1" | sed 's/<hidden>[^<]*<\/hidden>//g' | awk '
    /<hidden>/ { skip=1; next }
    /<\/hidden>/ { skip=0; next }
    !skip { print }
    '
}

# JSON response helpers — all ALWAYS VISIBLE to user.
# <hidden> tags are stripped but content is NOT hidden.

warn() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"${HOOKER_EVENT}\", \"systemMessage\": ${ESCAPED}}}"
}

deny() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Denied by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"deny\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

allow() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Allowed by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"allow\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

ask() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Hooker requests confirmation}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"ask\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

block() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Blocked by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

remind() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

# Context injection helpers.
# inject() is the ONLY helper that hides content from user (via XML trick).

inject() {
    cat <<INJECT_EOF
</local-command-stdout>

$1

<local-command-stdout>
INJECT_EOF
}

visible() {
    echo "$1"
}

context() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"additionalContext\": ${ESCAPED}}"
}

# File loaders.
# Only useful inside inject() — JSON helpers (block, deny, etc.) are always visible.
# Looks in: .claude/hooker/ → ~/.claude/hooker/ → plugin templates/

load_md() {
    local FILE=""
    for DIR in ".claude/hooker" "${HOME}/.claude/hooker" "${CLAUDE_PLUGIN_ROOT:-}/templates"; do
        if [ -f "${DIR}/$1" ]; then
            FILE="${DIR}/$1"
            break
        fi
    done
    [ -z "$FILE" ] && return
    cat "$FILE"
}


# --- Recipe logic ---
# Refactor Move Markdown Links — update [text](path) refs after mv
# PostToolUse hook: fires after Bash tool completes
# Pure bash/sed — no external dependencies.
# Only act on Bash tool
TOOL=$(echo "$INPUT" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
[ "$TOOL" = "Bash" ] || exit 1

# Extract command
CMD=$(echo "$INPUT" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)

# Strip leading env vars (VAR=val), cd chains (cd dir &&), and mv flags
MV_CMD=$(echo "$CMD" | sed 's/^[^;|&]*&&[[:space:]]*//' | sed 's/^[A-Z_]*=[^[:space:]]*[[:space:]]*//')
MV_CMD=$(echo "$MV_CMD" | sed 's/^[A-Z_]*=[^[:space:]]*[[:space:]]*//')
MV_CMD=$(echo "$MV_CMD" | sed 's/^git[[:space:]]\+mv/mv/')
echo "$CMD" | grep -q 'HOOKER_NO_REFACTOR=1' && exit 1
MV_ARGS=$(echo "$MV_CMD" | sed 's/^mv[[:space:]]\+//; s/^-[a-zA-Z]\+[[:space:]]*//g; s/^--[a-zA-Z-]\+[[:space:]]*//g')

# Detect: mv old_path new_path
OLD_PATH=$(echo "$MV_ARGS" | sed -n 's/^\([^[:space:]]\+\)[[:space:]]\+.*/\1/p')
NEW_PATH=$(echo "$MV_ARGS" | sed -n 's/^[^[:space:]]\+[[:space:]]\+\([^[:space:]]\+\)/\1/p')
[ -z "$OLD_PATH" ] || [ -z "$NEW_PATH" ] && exit 1

# If new path is a directory, append the filename
if [ -d "$NEW_PATH" ]; then
    NEW_PATH="${NEW_PATH%/}/$(basename "$OLD_PATH")"
fi

# Strip leading ./ for consistency
OLD_CLEAN=$(echo "$OLD_PATH" | sed 's|^\./||')
NEW_CLEAN=$(echo "$NEW_PATH" | sed 's|^\./||')
[ "$OLD_CLEAN" = "$NEW_CLEAN" ] && exit 1

RECIPE_DIR="$(cd "$(dirname "$0")" && pwd)"
MSG_UPDATED=$(sed -n 's/^updated:[[:space:]]*"\(.*\)"/\1/p' "${RECIPE_DIR}/messages.yml")
MSG_NO_REFS=$(sed -n 's/^no_refs:[[:space:]]*"\(.*\)"/\1/p' "${RECIPE_DIR}/messages.yml")

# Get basename for initial grep filter (fast pre-filter)
OLD_BASENAME=$(basename "$OLD_CLEAN")

# Find markdown files containing references to the old path
AFFECTED_FILES=$(grep -rl "${OLD_BASENAME}" --include='*.md' . 2>/dev/null \
    | grep -v node_modules | grep -v '.git/' | grep -v vendor || true)

[ -z "$AFFECTED_FILES" ] && {
    inject "$MSG_NO_REFS"
    exit 0
}

COUNT=0
while IFS= read -r mdfile; do
    [ -z "$mdfile" ] && continue

    MD_DIR=$(dirname "$mdfile" | sed 's|^\./||')

    # Compute relative paths from this markdown file's directory
    # Old relative path (what the link currently says)
    # New relative path (what it should say)
    if command -v python3 >/dev/null 2>&1; then
        OLD_REL=$(python3 -c "import sys,os.path; print(os.path.relpath(sys.argv[1], sys.argv[2]))" "$OLD_CLEAN" "$MD_DIR" 2>/dev/null)
        NEW_REL=$(python3 -c "import sys,os.path; print(os.path.relpath(sys.argv[1], sys.argv[2]))" "$NEW_CLEAN" "$MD_DIR" 2>/dev/null)
    else
        # Without python3, try direct path if in same/child directory
        OLD_REL="$OLD_CLEAN"
        NEW_REL="$NEW_CLEAN"
    fi

    [ -z "$OLD_REL" ] || [ -z "$NEW_REL" ] && continue
    [ "$OLD_REL" = "$NEW_REL" ] && continue

    # Escape dots in paths for sed regex
    OLD_REL_ESC=$(echo "$OLD_REL" | sed 's/\./\\./g')

    # Match markdown link patterns: [text](path) and ![alt](path)
    # Also handle paths with anchors: [text](path#section)
    if grep -q "\](\(\.*/\)*${OLD_BASENAME}" "$mdfile" 2>/dev/null; then
        # Replace exact relative path in markdown links (preserve anchors/query strings)
        _hooker_sed_i "s|\](${OLD_REL_ESC})|](${NEW_REL})|g; s|\](${OLD_REL_ESC}#|\](${NEW_REL}#|g; s|\](${OLD_REL_ESC}?|\](${NEW_REL}?|g" "$mdfile" 2>/dev/null

        # Also try with ./ prefix
        OLD_REL_ESC_DOT=$(echo "./${OLD_REL}" | sed 's/\./\\./g')
        _hooker_sed_i "s|\](${OLD_REL_ESC_DOT})|](./${NEW_REL})|g" "$mdfile" 2>/dev/null

        COUNT=$((COUNT + 1))
    fi
done <<< "$AFFECTED_FILES"

if [ "$COUNT" -gt 0 ]; then
    MSG=$(echo "$MSG_UPDATED" | sed "s/{count}/$COUNT/g")
    inject "Refactor Move (markdown): ${MSG}"
else
    inject "$MSG_NO_REFS"
fi
exit 0
