#!/bin/bash
# Hooker standalone execute.sh — compiled from match script + helpers
# Can be used directly in .claude/settings.json without hooker plugin.
# Generated by: cd src && go run .
# Hooker version: 1.0.0
#
# Exit code translation (standalone has no inject.sh to catch codes):
#   exit 0 → ok (pass through)
#   exit 1 → skip/no-match → translated to exit 0 (not an error)
#   exit 2+ → real error → translated to exit 1 (Claude Code shows "hook error")

INPUT=$(cat)
HOOKER_EVENT=$(echo "$INPUT" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_CWD=$(echo "$INPUT" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_TRANSCRIPT=$(echo "$INPUT" | sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
export HOOKER_EVENT HOOKER_CWD HOOKER_TRANSCRIPT

# --- Inlined helpers ---
# Hooker — helper functions for match scripts
# Source this in your match script: source "${HOOKER_HELPERS}"
# Then use: warn "message", deny "reason", allow, block "reason", etc.
#
# Cross-platform: works on Linux, macOS, and Windows (Git Bash).
# No dependencies on python3, perl, or tac.
#
# Visibility:
#   inject() — hidden from user by default (XML trick). Use <visible> tags to show parts.
#   JSON helpers (warn, deny, block, remind, allow, ask) — ALWAYS VISIBLE to user.
#     <hidden> tags are stripped but content is NOT hidden (Claude Code renders
#     JSON reason/message as plaintext — XML trick cannot escape JSON strings).
#   load_md "file.md" — only useful inside inject(), not inside JSON helpers.

# Extract a JSON string field value. Usage: echo "$JSON" | _hooker_json_field "field_name"
_hooker_json_field() {
    sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1
}

# Check if JSON contains a field with a specific value. Usage: echo "$JSON" | _hooker_json_match "field" "value"
_hooker_json_match() {
    grep -q "\"$1\"[[:space:]]*:[[:space:]]*\"*$2" 2>/dev/null
}

# JSON-escape stdin. No python3/perl dependency.
_hooker_json_escape() {
    awk '
    BEGIN { ORS=""; first=1 }
    {
        if (!first) printf "\\n"
        first=0
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        gsub(/\t/, "\\t")
        gsub(/\r/, "\\r")
        print
    }
    END { }
    ' | { IFS= read -r -d '' x || true; printf '"%s"' "$x"; }
}

# Portable sed-in-place. macOS sed requires '' after -i, GNU sed does not.
_hooker_sed_i() {
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "$@"
    else
        sed -i "$@"
    fi
}

# Reverse lines of a file. Portable replacement for tac.
_hooker_reverse() {
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}'
}

# Get last assistant turn from transcript. Filters noise (progress, hook_progress),
# stops at real user prompt (not tool_result).
# Real user prompts have "type":"user" WITHOUT "sourceToolAssistantUUID" on the same line.
# Usage: _hooker_last_turn "$TRANSCRIPT_PATH"
_hooker_last_turn() {
    local TRANSCRIPT="$1"
    [ -z "$TRANSCRIPT" ] || [ ! -f "$TRANSCRIPT" ] && return 1
    # Note: || true prevents SIGPIPE (141) when awk exits early and breaks the pipe.
    # Without it, set -o pipefail in callers treats SIGPIPE as failure.
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}' "$TRANSCRIPT" \
        | grep -v '"type":"progress"' | grep -v '"type":"hook_progress"' \
        | awk '/"type":"user"/ && !/sourceToolAssistantUUID/{exit} {print}' || true
}

# Strip <hidden> tags from a string, return visible part only.
# Handles both single-line (<hidden>...</hidden> on one line) and multiline.
_hooker_strip_hidden() {
    echo "$1" | sed 's/<hidden>[^<]*<\/hidden>//g' | awk '
    /<hidden>/ { skip=1; next }
    /<\/hidden>/ { skip=0; next }
    !skip { print }
    '
}

# Runtime resolution for multi-language match scripts.
# Supports any file extension with configurable runtimes.

# Default runtimes by file extension
_hooker_default_runtime() {
    case "$1" in
        sh|bash) echo "bash" ;;
        py)      echo "python3" ;;
        js|cjs|mjs) echo "node" ;;
        ts|mts)  echo "npx tsx" ;;
        go)      echo "go run" ;;
        php)     echo "php" ;;
        rb)      echo "ruby" ;;
        pl)      echo "perl" ;;
        *)       echo "" ;; # empty = execute directly (binary, unknown)
    esac
}

# Resolve runtime for a file extension.
# Priority: env HOOKER_RUNTIME_<ext> > project runtimes.conf > user runtimes.conf > defaults
_hooker_resolve_runtime() {
    local EXT="$1"

    # 1. Environment variable override (e.g. HOOKER_RUNTIME_py=python3.12)
    eval "local ENV_VAL=\${HOOKER_RUNTIME_${EXT}:-}"
    [ -n "$ENV_VAL" ] && echo "$ENV_VAL" && return

    # 2. Project runtimes.conf
    local PROJECT_CONF="${HOOKER_CWD:-.}/.claude/hooker/runtimes.conf"
    if [ -f "$PROJECT_CONF" ]; then
        local VAL
        VAL=$(grep "^${EXT}=" "$PROJECT_CONF" 2>/dev/null | head -1 | cut -d= -f2-)
        [ -n "$VAL" ] && echo "$VAL" && return
    fi

    # 3. User runtimes.conf
    local USER_CONF="${HOME}/.claude/hooker/runtimes.conf"
    if [ -f "$USER_CONF" ]; then
        local VAL
        VAL=$(grep "^${EXT}=" "$USER_CONF" 2>/dev/null | head -1 | cut -d= -f2-)
        [ -n "$VAL" ] && echo "$VAL" && return
    fi

    # 4. Built-in default
    _hooker_default_runtime "$EXT"
}

# Find match script for a hook event in a directory (any language).
# Shell (.sh) has priority for backward compat, then common langs, then any.
_hooker_find_match() {
    local DIR="$1" HOOK="$2"

    # Shell first (backward compat)
    [ -f "${DIR}/${HOOK}.match.sh" ] && echo "${DIR}/${HOOK}.match.sh" && return

    # Common extensions
    for EXT in py js ts go php rb pl; do
        [ -f "${DIR}/${HOOK}.match.${EXT}" ] && echo "${DIR}/${HOOK}.match.${EXT}" && return
    done

    # Fallback: any other extension
    for F in "${DIR}/${HOOK}".match.*; do
        [ -f "$F" ] && echo "$F" && return
    done

    return 1
}

# Execute a match script with the appropriate runtime.
# Reads from stdin, writes to stdout. Caller handles exit codes.
_hooker_run_match() {
    local SCRIPT="$1"
    local EXT="${SCRIPT##*.}"
    local RUNTIME
    RUNTIME=$(_hooker_resolve_runtime "$EXT")

    if [ -z "$RUNTIME" ]; then
        # No runtime = execute directly (binary or self-executing)
        "$SCRIPT"
    elif [ "$EXT" = "sh" ] || [ "$EXT" = "bash" ]; then
        # Shell: execute directly (has shebang, is +x)
        "$SCRIPT"
    else
        # Non-shell: invoke through runtime
        # shellcheck disable=SC2086
        $RUNTIME "$SCRIPT"
    fi
}

# JSON response helpers — all ALWAYS VISIBLE to user.
# <hidden> tags are stripped but content is NOT hidden.

warn() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"${HOOKER_EVENT}\", \"systemMessage\": ${ESCAPED}}}"
}

deny() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Denied by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"deny\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

allow() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Allowed by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"allow\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

ask() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Hooker requests confirmation}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"ask\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

block() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Blocked by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

remind() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

# Context injection helpers.
# inject() is the ONLY helper that hides content from user (via XML trick).

inject() {
    cat <<INJECT_EOF
</local-command-stdout>

$1

<local-command-stdout>
INJECT_EOF
}

visible() {
    echo "$1"
}

context() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"additionalContext\": ${ESCAPED}}"
}

# File loaders.
# Only useful inside inject() — JSON helpers (block, deny, etc.) are always visible.
# Looks in: .claude/hooker/ → ~/.claude/hooker/ → plugin templates/

load_md() {
    local FILE=""
    for DIR in ".claude/hooker" "${HOME}/.claude/hooker" "${CLAUDE_PLUGIN_ROOT:-}/templates"; do
        if [ -f "${DIR}/$1" ]; then
            FILE="${DIR}/$1"
            break
        fi
    done
    [ -z "$FILE" ] && return
    cat "$FILE"
}


# --- Exit code translation ---
_hooker_main() {
# Refactor Move C# — update namespace/using after mv
# Derives namespace from directory structure relative to .csproj location
TOOL=$(echo "$INPUT" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
[ "$TOOL" = "Bash" ] || return 1

CMD=$(echo "$INPUT" | sed -n 's/.*"command"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)

# Strip cd chains, env vars, flags, handle git mv
MV_CMD=$(echo "$CMD" | sed 's/^[^;|&]*&&[[:space:]]*//' | sed 's/^[A-Z_]*=[^[:space:]]*[[:space:]]*//')
MV_CMD=$(echo "$MV_CMD" | sed 's/^[A-Z_]*=[^[:space:]]*[[:space:]]*//')
MV_CMD=$(echo "$MV_CMD" | sed 's/^git[[:space:]]\+mv/mv/')
echo "$CMD" | grep -q 'HOOKER_NO_REFACTOR=1' && return 1
MV_ARGS=$(echo "$MV_CMD" | sed 's/^mv[[:space:]]\+//; s/^-[a-zA-Z]\+[[:space:]]*//g; s/^--[a-zA-Z-]\+[[:space:]]*//g')

# Detect: mv old.cs new.cs
OLD_PATH=$(echo "$MV_ARGS" | sed -n 's/^\([^[:space:]]\+\.cs\)[[:space:]]\+.*/\1/p')
NEW_PATH=$(echo "$MV_ARGS" | sed -n 's/^[^[:space:]]\+[[:space:]]\+\([^[:space:]]\+\)/\1/p')
[ -z "$OLD_PATH" ] || [ -z "$NEW_PATH" ] && return 1

if [ -d "$NEW_PATH" ]; then
    NEW_PATH="${NEW_PATH%/}/$(basename "$OLD_PATH")"
fi

RECIPE_DIR="$(cd "$(dirname "$0")" && pwd)"
MSG_UPDATED=$(sed -n 's/^updated:[[:space:]]*"\(.*\)"/\1/p' "${RECIPE_DIR}/messages.yml")
MSG_NO_REFS=$(sed -n 's/^no_refs:[[:space:]]*"\(.*\)"/\1/p' "${RECIPE_DIR}/messages.yml")

# Find nearest .csproj to determine project root and root namespace
find_csproj_dir() {
    local DIR="$1"
    while [ "$DIR" != "." ] && [ "$DIR" != "/" ]; do
        ls "$DIR"/*.csproj 2>/dev/null | head -1 | grep -q . && echo "$DIR" && return
        DIR=$(dirname "$DIR")
    done
    # Fallback: current directory
    ls ./*.csproj 2>/dev/null | head -1 | grep -q . && echo "." && return
    return 1
}

# Derive namespace from path relative to .csproj
# Convention: directory structure = namespace (MyProject/Models/User.cs → MyProject.Models)
path_to_namespace() {
    local FILE_PATH="$1"
    local PROJ_DIR
    PROJ_DIR=$(find_csproj_dir "$(dirname "$FILE_PATH")")
    if [ -n "$PROJ_DIR" ]; then
        # Get root namespace from .csproj (RootNamespace element) or project dir name
        local ROOT_NS
        ROOT_NS=$(sed -n 's/.*<RootNamespace>\([^<]*\)<.*/\1/p' "$PROJ_DIR"/*.csproj 2>/dev/null | head -1)
        [ -z "$ROOT_NS" ] && ROOT_NS=$(basename "$PROJ_DIR")

        local REL
        REL=$(echo "$FILE_PATH" | sed "s|^${PROJ_DIR}/||; s|/[^/]*\.cs$||; s|/|.|g")
        if [ -n "$REL" ] && [ "$REL" != "$(basename "$FILE_PATH" .cs)" ]; then
            echo "${ROOT_NS}.${REL}"
        else
            echo "$ROOT_NS"
        fi
    else
        # No .csproj — derive from full path
        echo "$FILE_PATH" | sed 's|^\./||; s|/[^/]*\.cs$||; s|/|.|g'
    fi
}

OLD_NS=$(path_to_namespace "$OLD_PATH")
NEW_NS=$(path_to_namespace "$NEW_PATH")
[ -z "$OLD_NS" ] || [ -z "$NEW_NS" ] && return 1
[ "$OLD_NS" = "$NEW_NS" ] && return 1

OLD_CLASS=$(basename "$OLD_PATH" .cs)
NEW_CLASS=$(basename "$NEW_PATH" .cs)

OLD_NS_ESC=$(echo "$OLD_NS" | sed 's/\./\\./g')

# Update namespace in moved file (both block-scoped and file-scoped)
if [ -f "$NEW_PATH" ]; then
    _hooker_sed_i "s|^namespace ${OLD_NS_ESC}|namespace ${NEW_NS}|" "$NEW_PATH" 2>/dev/null
fi

# If class was renamed, update class declaration
if [ "$OLD_CLASS" != "$NEW_CLASS" ] && [ -f "$NEW_PATH" ]; then
    _hooker_sed_i "s|class ${OLD_CLASS}|class ${NEW_CLASS}|g" "$NEW_PATH" 2>/dev/null
fi

# Find C# files with using statements referencing old namespace
AFFECTED_FILES=$(grep -rl "using.*${OLD_NS_ESC}" --include='*.cs' . 2>/dev/null \
    | grep -v '.git/' | grep -v '/bin/' | grep -v '/obj/' || true)

# Also find fully qualified references
FQ_FILES=$(grep -rl "${OLD_NS_ESC}\.${OLD_CLASS}" --include='*.cs' . 2>/dev/null \
    | grep -v '.git/' | grep -v '/bin/' | grep -v '/obj/' || true)

ALL_FILES=$(printf '%s\n%s' "$AFFECTED_FILES" "$FQ_FILES" | sort -u)

[ -z "$ALL_FILES" ] && {
    inject "$MSG_NO_REFS"
    return 0
}

COUNT=0
while IFS= read -r file; do
    [ -z "$file" ] && continue
    CHANGED=false

    # Replace using statements
    if grep -q "using[[:space:]]\+${OLD_NS_ESC};" "$file" 2>/dev/null; then
        _hooker_sed_i "s|using ${OLD_NS_ESC};|using ${NEW_NS};|g" "$file" 2>/dev/null
        CHANGED=true
    fi

    # Replace fully qualified references
    OLD_FQ="${OLD_NS}.${OLD_CLASS}"
    NEW_FQ="${NEW_NS}.${NEW_CLASS}"
    OLD_FQ_ESC=$(echo "$OLD_FQ" | sed 's/\./\\./g')
    if grep -q "${OLD_FQ_ESC}" "$file" 2>/dev/null; then
        _hooker_sed_i "s|${OLD_FQ_ESC}|${NEW_FQ}|g" "$file" 2>/dev/null
        CHANGED=true
    fi

    $CHANGED && COUNT=$((COUNT + 1))
done <<< "$ALL_FILES"

if [ "$COUNT" -gt 0 ]; then
    MSG=$(echo "$MSG_UPDATED" | sed "s/{count}/$COUNT/g")
    inject "Refactor Move (C#): ${MSG}"
else
    inject "$MSG_NO_REFS"
fi
return 0
}
_hooker_main
_EXIT=$?
if [ "$_EXIT" -eq 0 ]; then exit 0
elif [ "$_EXIT" -eq 1 ]; then exit 0   # skip/no-match → not an error
else exit 1                             # exit 2+ → real error
fi
