package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"hooker-build/generators"

	"github.com/nikolalohinski/gonja/v2"
	"github.com/nikolalohinski/gonja/v2/exec"
)

func main() {
	pluginFlag := flag.String("plugin", "all", "Plugin to build: hooker, all")
	flag.Parse()

	srcDir, _ := os.Getwd()
	if _, err := os.Stat(filepath.Join(srcDir, "build.go")); err != nil {
		srcDir, _ = filepath.Abs(filepath.Dir(os.Args[0]))
	}

	repoRoot := filepath.Join(srcDir, "..")

	switch *pluginFlag {
	case "hooker", "all":
		buildHooker(srcDir, repoRoot)
		buildMarketplace(srcDir, repoRoot)
	default:
		fmt.Fprintf(os.Stderr, "Unknown plugin: %s. Use hooker or all.\n", *pluginFlag)
		os.Exit(1)
	}

	fmt.Println("Done.")
}

// =============================================================================
// HOOKER BUILD
// =============================================================================

func buildHooker(srcDir, repoRoot string) {
	hookerSrc := filepath.Join(srcDir, "hooker")
	hookerOut := filepath.Join(repoRoot, "hooker")

	recipes := generators.LoadRecipes(hookerSrc)
	pluginVersion := readVersion(hookerSrc)


	ctx := exec.NewContext(map[string]any{
		"recipes":        recipes,
		"categories":     generators.GroupByCategory(recipes),
		"uncoveredHooks": generators.UncoveredHooks(recipes),
		"coveredHooks":   generators.CoveredHooks(recipes),
		"allHooks":       generators.AllHooks(),
	})

	fmt.Println("Building Hooker plugin...")

	// 1. Commands — gonja templates
	buildCommands(hookerSrc, hookerOut, ctx)

	// 2. Scripts — shell bundling (@bundle directives)
	buildScripts(hookerSrc, hookerOut)

	// 3. Recipes — copy as-is + compile execute.sh
	copyDir(filepath.Join(hookerSrc, "recipes"), filepath.Join(hookerOut, "recipes"), "recipes")
	compileExecutables(hookerSrc, hookerOut, pluginVersion)
	copyDir(filepath.Join(hookerSrc, "hooks"), filepath.Join(hookerOut, "hooks"), "hooks")
	copyDir(filepath.Join(hookerSrc, "templates"), filepath.Join(hookerOut, "templates"), "templates")

	// 3b. Multi-language helpers (Python, JS) — for non-shell match scripts
	copyDir(filepath.Join(hookerSrc, "helpers"), filepath.Join(hookerOut, "helpers"), "helpers")

	// 4. Plugin manifest
	copyFile(filepath.Join(hookerSrc, "plugin.json"), filepath.Join(hookerOut, ".claude-plugin", "plugin.json"), "plugin.json")

	// 5. .pluginignore
	copyFile(filepath.Join(hookerSrc, ".pluginignore"), filepath.Join(hookerOut, ".pluginignore"), ".pluginignore")

	// 6. README.md — gonja template
	buildFile(filepath.Join(hookerSrc, "README.md"), filepath.Join(hookerOut, "README.md"), "README.md", ctx)

	// 7. Plugin-recipes — recipes with "plugin" field also build as standalone plugins
	buildPluginRecipes(hookerSrc, hookerOut, repoRoot, recipes)
}

// =============================================================================
// PLUGIN-RECIPE BUILD
// Recipes with "plugin": {"output": "..."} in recipe.json also build as
// standalone plugins into {repoRoot}/{output}/.
// =============================================================================

func buildPluginRecipes(hookerSrc, hookerOut, repoRoot string, recipes []generators.Recipe) {
	for _, r := range recipes {
		if r.Plugin == nil {
			continue
		}
		recipeDir := filepath.Join(hookerSrc, "recipes", r.ID)
		compiledDir := filepath.Join(hookerOut, "recipes", r.ID)
		outDir := filepath.Join(repoRoot, r.Plugin.Output)

		fmt.Printf("Building plugin-recipe: %s → %s/\n", r.ID, r.Plugin.Output)
		os.RemoveAll(outDir)
		os.MkdirAll(outDir, 0755)

		// 1. Copy recipe files (skip recipe.json, plugin.json, hooks/)
		copyPluginRecipeFiles(recipeDir, outDir)

		// 2. Auto-detect hook scripts and copy to output
		hookScripts := detectHookScripts(recipeDir, compiledDir, outDir, r.Hooks)

		// 3. Generate hooks/hooks.json
		generateHooksJson(outDir, r, hookScripts)

		// 4. Generate .claude-plugin/plugin.json
		generatePluginJson(outDir, r)

		fmt.Printf("  %s: done (%d hooks)\n", r.Plugin.Output, len(hookScripts))
	}
}

// copyPluginRecipeFiles copies recipe files, skipping build-generated artifacts.
func copyPluginRecipeFiles(src, dst string) {
	count := 0
	filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, path)

		// Skip files/dirs that are generated by the build
		switch {
		case rel == "recipe.json":
			return nil
		case rel == "plugin.json":
			return nil
		case rel == "hooks" || strings.HasPrefix(rel, "hooks"+string(filepath.Separator)):
			return nil
		}

		if info.IsDir() {
			os.MkdirAll(filepath.Join(dst, rel), 0755)
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		writeFile(target, data)
		if info.Mode()&0111 != 0 {
			os.Chmod(target, 0755)
		}
		count++
		return nil
	})
	fmt.Printf("  files: %d copied\n", count)
}

// detectHookScripts finds hook scripts in the recipe and compiled dirs.
// Returns map of hook name → script filename in the output dir.
//
// Detection order per hook:
//   1. {Hook}.match.sh in source → use compiled {Hook}.execute.sh
//   2. {Hook}.sh in source → standalone, copy as-is
func detectHookScripts(recipeDir, compiledDir, outDir string, hooks []string) map[string]string {
	result := make(map[string]string)

	for _, hook := range hooks {
		// Try {Hook}.match.sh → compiled execute.sh
		matchSrc := filepath.Join(recipeDir, hook+".match.sh")
		if _, err := os.Stat(matchSrc); err == nil {
			execName := hook + ".execute.sh"
			execSrc := filepath.Join(compiledDir, execName)
			if data, err := os.ReadFile(execSrc); err == nil {
				writeFile(filepath.Join(outDir, execName), data)
				os.Chmod(filepath.Join(outDir, execName), 0755)
				result[hook] = execName
				fmt.Printf("  %s: %s.match.sh → %s (compiled)\n", hook, hook, execName)
				continue
			}
		}

		// Try {Hook}.sh → standalone
		shSrc := filepath.Join(recipeDir, hook+".sh")
		if _, err := os.Stat(shSrc); err == nil {
			shName := hook + ".sh"
			// Already copied by copyPluginRecipeFiles
			result[hook] = shName
			fmt.Printf("  %s: %s (standalone)\n", hook, shName)
			continue
		}

		fmt.Fprintf(os.Stderr, "  WARNING: no script found for hook %s in %s\n", hook, recipeDir)
	}

	return result
}

// generateHooksJson writes hooks/hooks.json from recipe metadata + detected scripts.
func generateHooksJson(outDir string, r generators.Recipe, hookScripts map[string]string) {
	type hookEntry struct {
		Type    string `json:"type"`
		Command string `json:"command"`
	}
	type hookDef struct {
		Matcher string      `json:"matcher"`
		Hooks   []hookEntry `json:"hooks"`
	}

	hooks := make(map[string][]hookDef)
	for hookName, scriptName := range hookScripts {
		matcher := ""
		if r.Matchers != nil {
			matcher = r.Matchers[hookName]
		}
		hooks[hookName] = []hookDef{{
			Matcher: matcher,
			Hooks: []hookEntry{{
				Type:    "command",
				Command: "${CLAUDE_PLUGIN_ROOT}/" + scriptName,
			}},
		}}
	}

	wrapper := map[string]any{"hooks": hooks}
	data, err := json.MarshalIndent(wrapper, "", "  ")
	if err != nil {
		fatal("hooks.json", "marshaling", err)
	}
	data = append(data, '\n')

	hooksDir := filepath.Join(outDir, "hooks")
	os.MkdirAll(hooksDir, 0755)
	writeFile(filepath.Join(hooksDir, "hooks.json"), data)
	fmt.Printf("  hooks.json: generated (%d hooks)\n", len(hooks))
}

// generatePluginJson writes .claude-plugin/plugin.json from recipe metadata.
func generatePluginJson(outDir string, r generators.Recipe) {
	plugin := map[string]any{
		"name":        r.Plugin.Output,
		"description": r.Description,
		"version":     r.Version,
	}
	if r.Attribution != nil {
		author := map[string]string{"name": r.Attribution.Author}
		if r.Attribution.URL != "" {
			author["url"] = r.Attribution.URL
		}
		plugin["author"] = author
		if r.Attribution.License != "" {
			plugin["license"] = r.Attribution.License
		}
	}

	data, err := json.MarshalIndent(plugin, "", "  ")
	if err != nil {
		fatal("plugin.json", "marshaling", err)
	}
	data = append(data, '\n')

	os.MkdirAll(filepath.Join(outDir, ".claude-plugin"), 0755)
	writeFile(filepath.Join(outDir, ".claude-plugin", "plugin.json"), data)
	fmt.Printf("  plugin.json: generated (v%s)\n", r.Version)
}

// =============================================================================
// MARKETPLACE — shared, reads both plugin.json versions
// =============================================================================

func buildMarketplace(srcDir, repoRoot string) {
	hookerVersion := readVersion(filepath.Join(srcDir, "hooker"))

	plugins := []map[string]string{
		{
			"name":        "hooker",
			"source":      "./hooker",
			"description": "Universal hook injection framework. Inject prompts, reminders, and guardrails into 25+ Claude Code hook events.",
			"version":     hookerVersion,
		},
	}

	// Add plugin-recipes dynamically
	for _, r := range generators.LoadRecipes(filepath.Join(srcDir, "hooker")) {
		if r.Plugin == nil {
			continue
		}
		plugins = append(plugins, map[string]string{
			"name":        r.Plugin.Output,
			"source":      "./" + r.Plugin.Output,
			"description": r.Description,
			"version":     r.Version,
		})
	}

	marketplace := map[string]any{
		"name":    "hooker-marketplace",
		"owner":   map[string]string{"name": "treetank"},
		"plugins": plugins,
	}

	data, err := json.MarshalIndent(marketplace, "", "  ")
	if err != nil {
		fatal("marketplace.json", "marshaling", err)
	}
	data = append(data, '\n')

	// CC defaults to .claude-plugin/marketplace.json when resolving marketplaces
	os.MkdirAll(filepath.Join(repoRoot, ".claude-plugin"), 0755)
	writeFile(filepath.Join(repoRoot, ".claude-plugin", "marketplace.json"), data)
	fmt.Println("  .claude-plugin/marketplace.json: built")
}

// =============================================================================
// SHARED BUILD FUNCTIONS
// =============================================================================

// --- Commands: Gonja templates ---

func buildCommands(pluginSrc, pluginOut string, ctx *exec.Context) {
	srcCommands := filepath.Join(pluginSrc, "commands")
	outCommands := filepath.Join(pluginOut, "commands")

	os.MkdirAll(outCommands, 0755)

	entries, err := os.ReadDir(srcCommands)
	if err != nil {
		fmt.Fprintf(os.Stderr, "  commands/: ERROR — %v\n", err)
		os.Exit(1)
	}

	hasTemplating := regexp.MustCompile(`\{[{%#]`)

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}

		srcPath := filepath.Join(srcCommands, e.Name())
		outPath := filepath.Join(outCommands, e.Name())
		data, err := os.ReadFile(srcPath)
		if err != nil {
			fatal(e.Name(), "reading", err)
		}

		src := string(data)
		if !hasTemplating.MatchString(src) {
			writeFile(outPath, data)
			fmt.Printf("  commands/%s: copied\n", e.Name())
			continue
		}

		tpl, err := gonja.FromString(src)
		if err != nil {
			fatal("commands/"+e.Name(), "parsing", err)
		}

		result, err := tpl.ExecuteToString(ctx)
		if err != nil {
			fatal("commands/"+e.Name(), "rendering", err)
		}

		writeFile(outPath, []byte(result))
		fmt.Printf("  commands/%s: built\n", e.Name())
	}
}

// --- Scripts: Shell bundling ---
// Resolves `# @bundle path/to/file.sh` directives by inlining file contents.

func buildScripts(pluginSrc, pluginOut string) {
	srcScripts := filepath.Join(pluginSrc, "scripts")
	outScripts := filepath.Join(pluginOut, "scripts")

	entries, err := os.ReadDir(srcScripts)
	if err != nil {
		return
	}

	os.MkdirAll(outScripts, 0755)

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".sh") {
			continue
		}

		srcPath := filepath.Join(srcScripts, e.Name())
		outPath := filepath.Join(outScripts, e.Name())

		result, err := bundleShell(srcPath, srcScripts)
		if err != nil {
			fatal("scripts/"+e.Name(), "bundling", err)
		}

		writeFile(outPath, []byte(result))
		os.Chmod(outPath, 0755)
		fmt.Printf("  scripts/%s: bundled\n", e.Name())
	}
}

func bundleShell(path, baseDir string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	var out strings.Builder
	scanner := bufio.NewScanner(file)
	bundleRe := regexp.MustCompile(`^#\s*@bundle\s+(.+)$`)

	for scanner.Scan() {
		line := scanner.Text()

		if m := bundleRe.FindStringSubmatch(line); m != nil {
			includePath := filepath.Join(baseDir, m[1])
			content, err := os.ReadFile(includePath)
			if err != nil {
				return "", fmt.Errorf("@bundle %s: %w", m[1], err)
			}
			// Strip leading comments/blank lines from included file
			text := strings.TrimSpace(string(content))
			out.WriteString(text)
			out.WriteString("\n\n")
		} else {
			out.WriteString(line)
			out.WriteString("\n")
		}
	}

	return out.String(), scanner.Err()
}

// --- Single file: gonja template or copy ---

func buildFile(srcPath, outPath, label string, ctx *exec.Context) {
	data, err := os.ReadFile(srcPath)
	if err != nil {
		if os.IsNotExist(err) {
			return
		}
		fatal(label, "reading", err)
	}

	src := string(data)
	hasTemplating := regexp.MustCompile(`\{[{%#]`).MatchString(src)

	if !hasTemplating {
		writeFile(outPath, data)
		fmt.Printf("  %s: copied\n", label)
		return
	}

	tpl, err := gonja.FromString(src)
	if err != nil {
		fatal(label, "parsing", err)
	}

	result, err := tpl.ExecuteToString(ctx)
	if err != nil {
		fatal(label, "rendering", err)
	}

	writeFile(outPath, []byte(result))
	fmt.Printf("  %s: built\n", label)
}

// --- Static copy ---

func copyDir(src, dst, label string) {
	if _, err := os.Stat(src); os.IsNotExist(err) {
		return
	}

	count := 0
	filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, path)
		target := filepath.Join(dst, rel)

		if info.IsDir() {
			os.MkdirAll(target, 0755)
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		writeFile(target, data)
		// Preserve executable bit
		if info.Mode()&0111 != 0 {
			os.Chmod(target, 0755)
		}
		count++
		return nil
	})
	fmt.Printf("  %s/: %d files copied\n", label, count)
}

func copyFile(src, dst, label string) {
	if _, err := os.Stat(src); os.IsNotExist(err) {
		return
	}
	data, err := os.ReadFile(src)
	if err != nil {
		fatal(label, "reading", err)
	}
	os.MkdirAll(filepath.Dir(dst), 0755)
	writeFile(dst, data)
	fmt.Printf("  %s: copied\n", label)
}

// --- Read plugin version ---

func readVersion(pluginSrcDir string) string {
	data, err := os.ReadFile(filepath.Join(pluginSrcDir, "plugin.json"))
	if err != nil {
		return "unknown"
	}
	re := regexp.MustCompile(`"version"\s*:\s*"([^"]+)"`)
	m := re.FindSubmatch(data)
	if m != nil {
		return string(m[1])
	}
	return "unknown"
}

// --- Compile standalone executables for recipes ---

func compileExecutables(pluginSrc, pluginOut, version string) {
	// Load bundled helpers.sh
	helpersPath := filepath.Join(pluginOut, "scripts", "helpers.sh")
	helpersContent, err := os.ReadFile(helpersPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "  execute: WARNING — cannot read helpers.sh: %v\n", err)
		return
	}

	// Load multi-language helpers
	pyHelpersContent, _ := os.ReadFile(filepath.Join(pluginSrc, "helpers", "hooker_helpers.py"))
	jsHelpersContent, _ := os.ReadFile(filepath.Join(pluginSrc, "helpers", "hooker_helpers.js"))

	recipesDir := filepath.Join(pluginSrc, "recipes")
	entries, err := os.ReadDir(recipesDir)
	if err != nil {
		return
	}

	preamble := fmt.Sprintf(`#!/bin/bash
# Hooker standalone execute.sh — compiled from match script + helpers
# Can be used directly in .claude/settings.json without hooker plugin.
# Generated by: cd src && go run .
# Hooker version: %s
#
# Exit code translation (standalone has no inject.sh to catch codes):
#   exit 0 → ok (pass through)
#   exit 1 → skip/no-match → translated to exit 0 (not an error)
#   exit 2+ → real error → translated to exit 1 (Claude Code shows "hook error")

INPUT=$(cat)`, version) + `
HOOKER_EVENT=$(echo "$INPUT" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_CWD=$(echo "$INPUT" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_TRANSCRIPT=$(echo "$INPUT" | sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
export HOOKER_EVENT HOOKER_CWD HOOKER_TRANSCRIPT

`

	// Epilogue wraps the recipe body in _hooker_main, translates exit codes
	epilogue := `
# --- Exit code translation ---
_hooker_main() {
`

	epilogueEnd := `
}
_hooker_main
_EXIT=$?
if [ "$_EXIT" -eq 0 ]; then exit 0
elif [ "$_EXIT" -eq 1 ]; then exit 0   # skip/no-match → not an error
else exit 1                             # exit 2+ → real error
fi
`

	mdHandler := fmt.Sprintf(`#!/bin/bash
# Hooker standalone execute.sh — compiled from .md template
# Can be used directly in .claude/settings.json without hooker plugin.
# Generated by: cd src && go run .
# Hooker version: %s`, version) + `

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE="${SCRIPT_DIR}/%s"

ACTION=$(awk '/^---$/{n++; next} n==1 && /^type:/{gsub(/^type:[[:space:]]*/, ""); print; exit}' "$TEMPLATE")
CONTENT=$(awk 'BEGIN{n=0} /^---$/{n++; next} n>=2{print}' "$TEMPLATE")
CONTENT=$(echo "$CONTENT" | sed -e '/./,$!d' -e :a -e '/^\n*$/{$d;N;ba;}')
[ -z "$ACTION" ] && ACTION="inject"
[ -z "$CONTENT" ] && exit 0

case "$ACTION" in
    inject)
        cat <<INJECT_EOF
</local-command-stdout>

${CONTENT}

<local-command-stdout>
INJECT_EOF
        ;;
    *)
        echo "$CONTENT"
        ;;
esac
`

	count := 0
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		recipeDir := filepath.Join(recipesDir, e.Name())
		outDir := filepath.Join(pluginOut, "recipes", e.Name())

		hookFiles, _ := os.ReadDir(recipeDir)
		for _, hf := range hookFiles {
			name := hf.Name()

			// Compile .match.sh → .execute.sh
			if strings.HasSuffix(name, ".match.sh") {
				hookName := strings.TrimSuffix(name, ".match.sh")
				matchPath := filepath.Join(recipeDir, name)
				outPath := filepath.Join(outDir, hookName+".execute.sh")

				matchContent, err := os.ReadFile(matchPath)
				if err != nil {
					continue
				}

				// Remove shebang and source HOOKER_HELPERS line
				body := string(matchContent)
				body = regexp.MustCompile(`(?m)^#!.*\n`).ReplaceAllString(body, "")
				body = regexp.MustCompile(`(?m)^source\s+"\$\{HOOKER_HELPERS\}"\s*\n`).ReplaceAllString(body, "")
				// Remove INPUT=$(cat) — preamble handles it
				body = regexp.MustCompile(`(?m)^INPUT=\$\(cat\)\s*\n`).ReplaceAllString(body, "")
				body = strings.TrimSpace(body)
				body = regexp.MustCompile(`\bexit (\d+)`).ReplaceAllString(body, "return $1")

				var out strings.Builder
				out.WriteString(preamble)
				out.WriteString("# --- Inlined helpers ---\n")
				h := string(helpersContent)
				h = regexp.MustCompile(`(?m)^#!.*\n`).ReplaceAllString(h, "")
				out.WriteString(h)
				out.WriteString(epilogue)
				out.WriteString(body)
				out.WriteString(epilogueEnd)

				writeFile(outPath, []byte(out.String()))
				os.Chmod(outPath, 0755)
				count++
			}

			// Compile .match.py → .execute.py
			if strings.HasSuffix(name, ".match.py") && len(pyHelpersContent) > 0 {
				hookName := strings.TrimSuffix(name, ".match.py")
				matchPath := filepath.Join(recipeDir, name)
				outPath := filepath.Join(outDir, hookName+".execute.py")

				matchContent, err := os.ReadFile(matchPath)
				if err != nil {
					continue
				}

				body := string(matchContent)
				body = regexp.MustCompile(`(?m)^#!.*\n`).ReplaceAllString(body, "")
				body = regexp.MustCompile(`(?m)^from hooker_helpers import.*\n`).ReplaceAllString(body, "")
				body = regexp.MustCompile(`(?m)^import hooker_helpers.*\n`).ReplaceAllString(body, "")
				body = strings.TrimSpace(body)

				helpers := string(pyHelpersContent)
				helpers = regexp.MustCompile(`(?ms)^""".*?"""\n`).ReplaceAllString(helpers, "")
				helpers = regexp.MustCompile(`(?m)^import json\n`).ReplaceAllString(helpers, "")
				helpers = regexp.MustCompile(`(?m)^import sys\n`).ReplaceAllString(helpers, "")
				helpers = regexp.MustCompile(`(?m)^import os\n`).ReplaceAllString(helpers, "")
				helpers = strings.TrimSpace(helpers)

				compiled := fmt.Sprintf(`#!/usr/bin/env python3
# Hooker standalone execute.py — compiled from match script + helpers
# Can be used directly in .claude/settings.json without hooker plugin.
# Generated by: cd src && go run .
# Hooker version: %s
#
# Usage in settings.json:
#   { "command": "python3 \"$CLAUDE_PROJECT_DIR/.claude/hooker/{recipe}/%s.execute.py\"" }

import json
import sys
import os

# --- Inlined helpers ---
%s

# --- Recipe ---
def _hooker_main():
    %s

try:
    _hooker_main()
    sys.exit(0)
except SystemExit as e:
    code = e.code if isinstance(e.code, int) else 1
    if code <= 1:
        sys.exit(0)   # match or skip → not an error
    else:
        sys.exit(1)   # real error → Claude Code shows "hook error"
`, version, hookName, helpers, strings.ReplaceAll(body, "\n", "\n    "))

				writeFile(outPath, []byte(compiled))
				os.Chmod(outPath, 0755)
				count++
			}

			// Compile .match.js → .execute.js (also used for .match.ts → .execute.js)
			if (strings.HasSuffix(name, ".match.js") || strings.HasSuffix(name, ".match.ts")) && len(jsHelpersContent) > 0 {
				ext := filepath.Ext(name)
				hookName := strings.TrimSuffix(strings.TrimSuffix(name, ".match.js"), ".match.ts")
				matchPath := filepath.Join(recipeDir, name)
				outPath := filepath.Join(outDir, hookName+".execute.js")

				matchContent, err := os.ReadFile(matchPath)
				if err != nil {
					continue
				}

				body := string(matchContent)
				body = regexp.MustCompile(`(?m)^#!.*\n`).ReplaceAllString(body, "")
				varNameMatch := regexp.MustCompile(`(?m)^const (\w+) = require\(['"]hooker_helpers['"]\)`).FindStringSubmatch(body)
				body = regexp.MustCompile(`(?m)^const .+ = require\(['"]hooker_helpers['"]\);?\n`).ReplaceAllString(body, "")
				body = regexp.MustCompile(`(?m)^const \{[^}]+\} = require\(['"]hooker_helpers['"]\);?\n`).ReplaceAllString(body, "")
				body = regexp.MustCompile(`(?m)^import .+ from ['"]hooker_helpers['"];?\n`).ReplaceAllString(body, "")
				if len(varNameMatch) > 1 {
					prefix := varNameMatch[1] + "."
					body = strings.ReplaceAll(body, prefix, "")
				}
				if ext == ".ts" {
					body = regexp.MustCompile(`:\s*(string|number|boolean|any|object|void|Record<[^>]+>|[A-Z]\w*(?:\[\])?)\s*=`).ReplaceAllString(body, " =")
					body = regexp.MustCompile(`(?m)^import .+ from ['"][^'"]+['"];?\n`).ReplaceAllString(body, "")
				}
				body = strings.TrimSpace(body)

				helpers := string(jsHelpersContent)
				helpers = regexp.MustCompile(`(?ms)^/\*\*.*?\*/\n*`).ReplaceAllString(helpers, "")
				helpers = regexp.MustCompile(`(?m)^const fs = require\('fs'\);?\n`).ReplaceAllString(helpers, "")
				helpers = regexp.MustCompile(`(?ms)^module\.exports = \{[^}]*\};?\n?`).ReplaceAllString(helpers, "")
				helpers = strings.TrimSpace(helpers)

				compiled := fmt.Sprintf(`#!/usr/bin/env node
// Hooker standalone execute.js — compiled from match script + helpers
// Can be used directly in .claude/settings.json without hooker plugin.
// Generated by: cd src && go run .
// Hooker version: %s
//
// Usage in settings.json:
//   { "command": "node \"$CLAUDE_PROJECT_DIR/.claude/hooker/{recipe}/%s.execute.js\"" }

const fs = require('fs');

// --- Exit code translation ---
const _origExit = process.exit;
process.exit = function(code) {
    if (typeof code === 'number' && code <= 1) _origExit(0);   // match or skip
    else _origExit(1);                                          // real error
};

// --- Inlined helpers ---
%s

// --- Recipe ---
%s
`, version, hookName, helpers, body)

				writeFile(outPath, []byte(compiled))
				os.Chmod(outPath, 0755)
				count++
			}

			// Compile .md (without matching .match.*) → .execute.sh
			if strings.HasSuffix(name, ".md") {
				hookName := strings.TrimSuffix(name, ".md")
				matchExists := false
				for _, check := range hookFiles {
					cn := check.Name()
					if strings.HasPrefix(cn, hookName+".match.") {
						matchExists = true
						break
					}
				}
				if matchExists {
					continue
				}

				outPath := filepath.Join(outDir, hookName+".execute.sh")
				compiled := fmt.Sprintf(mdHandler, name)
				writeFile(outPath, []byte(compiled))
				os.Chmod(outPath, 0755)
				count++
			}
		}
	}
	fmt.Printf("  recipes/: %d standalone executables compiled\n", count)
}

// =============================================================================
// HELPERS
// =============================================================================

func writeFile(path string, data []byte) {
	if err := os.WriteFile(path, data, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR writing %s: %v\n", path, err)
		os.Exit(1)
	}
}

func fatal(name, action string, err error) {
	fmt.Fprintf(os.Stderr, "  %s: ERROR %s — %v\n", name, action, err)
	os.Exit(1)
}
