#!/bin/bash
# Hooker standalone execute.sh — compiled from match script + helpers
# Can be used directly in .claude/settings.json without hooker plugin.
# Generated by: cd src && go run .
# Hooker version: 0.23.0

INPUT=$(cat)
HOOKER_EVENT=$(echo "$INPUT" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_CWD=$(echo "$INPUT" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_TRANSCRIPT=$(echo "$INPUT" | sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
export HOOKER_EVENT HOOKER_CWD HOOKER_TRANSCRIPT

# --- Inlined helpers ---
# Hooker — helper functions for match scripts
# Source this in your match script: source "${HOOKER_HELPERS}"
# Then use: warn "message", deny "reason", allow, block "reason", etc.
#
# Cross-platform: works on Linux, macOS, and Windows (Git Bash).
# No dependencies on python3, perl, or tac.
#
# Visibility:
#   inject() — hidden from user by default (XML trick). Use <visible> tags to show parts.
#   JSON helpers (warn, deny, block, remind, allow, ask) — ALWAYS VISIBLE to user.
#     <hidden> tags are stripped but content is NOT hidden (Claude Code renders
#     JSON reason/message as plaintext — XML trick cannot escape JSON strings).
#   load_md "file.md" — only useful inside inject(), not inside JSON helpers.

# Extract a JSON string field value. Usage: echo "$JSON" | _hooker_json_field "field_name"
_hooker_json_field() {
    sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1
}

# Check if JSON contains a field with a specific value. Usage: echo "$JSON" | _hooker_json_match "field" "value"
_hooker_json_match() {
    grep -q "\"$1\"[[:space:]]*:[[:space:]]*\"*$2" 2>/dev/null
}

# JSON-escape stdin. No python3/perl dependency.
_hooker_json_escape() {
    awk '
    BEGIN { ORS=""; first=1 }
    {
        if (!first) printf "\\n"
        first=0
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        gsub(/\t/, "\\t")
        gsub(/\r/, "\\r")
        print
    }
    END { }
    ' | { IFS= read -r -d '' x || true; printf '"%s"' "$x"; }
}

# Portable sed-in-place. macOS sed requires '' after -i, GNU sed does not.
_hooker_sed_i() {
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "$@"
    else
        sed -i "$@"
    fi
}

# Reverse lines of a file. Portable replacement for tac.
_hooker_reverse() {
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}'
}

# Get last assistant turn from transcript. Filters noise (progress, hook_progress),
# stops at real user prompt (not tool_result).
# Real user prompts have "type":"user" WITHOUT "sourceToolAssistantUUID" on the same line.
# Usage: _hooker_last_turn "$TRANSCRIPT_PATH"
_hooker_last_turn() {
    local TRANSCRIPT="$1"
    [ -z "$TRANSCRIPT" ] || [ ! -f "$TRANSCRIPT" ] && return 1
    # Note: || true prevents SIGPIPE (141) when awk exits early and breaks the pipe.
    # Without it, set -o pipefail in callers treats SIGPIPE as failure.
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}' "$TRANSCRIPT" \
        | grep -v '"type":"progress"' | grep -v '"type":"hook_progress"' \
        | awk '/"type":"user"/ && !/sourceToolAssistantUUID/{exit} {print}' || true
}

# Strip <hidden> tags from a string, return visible part only.
# Handles both single-line (<hidden>...</hidden> on one line) and multiline.
_hooker_strip_hidden() {
    echo "$1" | sed 's/<hidden>[^<]*<\/hidden>//g' | awk '
    /<hidden>/ { skip=1; next }
    /<\/hidden>/ { skip=0; next }
    !skip { print }
    '
}

# JSON response helpers — all ALWAYS VISIBLE to user.
# <hidden> tags are stripped but content is NOT hidden.

warn() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"${HOOKER_EVENT}\", \"systemMessage\": ${ESCAPED}}}"
}

deny() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Denied by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"deny\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

allow() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Allowed by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"allow\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

ask() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Hooker requests confirmation}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"ask\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

block() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Blocked by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

remind() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

# Context injection helpers.
# inject() is the ONLY helper that hides content from user (via XML trick).

inject() {
    cat <<INJECT_EOF
</local-command-stdout>

$1

<local-command-stdout>
INJECT_EOF
}

visible() {
    echo "$1"
}

context() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"additionalContext\": ${ESCAPED}}"
}

# File loaders.
# Only useful inside inject() — JSON helpers (block, deny, etc.) are always visible.
# Looks in: .claude/hooker/ → ~/.claude/hooker/ → plugin templates/

load_md() {
    local FILE=""
    for DIR in ".claude/hooker" "${HOME}/.claude/hooker" "${CLAUDE_PLUGIN_ROOT:-}/templates"; do
        if [ -f "${DIR}/$1" ]; then
            FILE="${DIR}/$1"
            break
        fi
    done
    [ -z "$FILE" ] && return
    cat "$FILE"
}


# --- Recipe logic ---
# Refactor Move Symbol — detect function/class moves between files
# PostToolUse hook: fires after Edit tool completes
# Uses Python script for diff analysis and state tracking.
# Only act on Edit tool
TOOL=$(echo "$INPUT" | sed -n 's/.*"tool_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
[ "$TOOL" = "Edit" ] || exit 1

# Need python3 for analysis
command -v python3 >/dev/null 2>&1 || exit 1

RECIPE_DIR="$(cd "$(dirname "$0")" && pwd)"

# Load messages
MSG_DETECTED=$(sed -n 's/^detected:[[:space:]]*"\(.*\)"/\1/p' "${RECIPE_DIR}/messages.yml")
MSG_TRACKED=$(sed -n 's/^removal_tracked:[[:space:]]*"\(.*\)"/\1/p' "${RECIPE_DIR}/messages.yml")

# Run detection
RESULT=$(echo "$INPUT" | python3 "${RECIPE_DIR}/detect-move.py" 2>/dev/null)
[ -z "$RESULT" ] && exit 1

ACTION=$(echo "$RESULT" | sed -n 's/.*"action"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')

case "$ACTION" in
    move_detected)
        SYMBOL=$(echo "$RESULT" | sed -n 's/.*"symbol"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
        FROM=$(echo "$RESULT" | sed -n 's/.*"from"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
        TO=$(echo "$RESULT" | sed -n 's/.*"to"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
        REFS=$(echo "$RESULT" | sed -n 's/.*"references"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p')

        MSG=$(echo "$MSG_DETECTED" | sed "s|{symbol}|$SYMBOL|g; s|{from}|$FROM|g; s|{to}|$TO|g; s|{count}|${REFS:-0}|g")
        inject "$MSG"
        exit 0
        ;;
    removal_tracked)
        # Silent — just tracking, don't bother the agent unless configured to
        exit 1
        ;;
    *)
        exit 1
        ;;
esac
