#!/bin/bash
# Hooker standalone execute.sh — compiled from match script + helpers
# Can be used directly in .claude/settings.json without hooker plugin.
# Generated by: cd src && go run .
# Hooker version: 0.24.0

INPUT=$(cat)
HOOKER_EVENT=$(echo "$INPUT" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_CWD=$(echo "$INPUT" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_TRANSCRIPT=$(echo "$INPUT" | sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
export HOOKER_EVENT HOOKER_CWD HOOKER_TRANSCRIPT

# --- Inlined helpers ---
# Hooker — helper functions for match scripts
# Source this in your match script: source "${HOOKER_HELPERS}"
# Then use: warn "message", deny "reason", allow, block "reason", etc.
#
# Cross-platform: works on Linux, macOS, and Windows (Git Bash).
# No dependencies on python3, perl, or tac.
#
# Visibility:
#   inject() — hidden from user by default (XML trick). Use <visible> tags to show parts.
#   JSON helpers (warn, deny, block, remind, allow, ask) — ALWAYS VISIBLE to user.
#     <hidden> tags are stripped but content is NOT hidden (Claude Code renders
#     JSON reason/message as plaintext — XML trick cannot escape JSON strings).
#   load_md "file.md" — only useful inside inject(), not inside JSON helpers.

# Extract a JSON string field value. Usage: echo "$JSON" | _hooker_json_field "field_name"
_hooker_json_field() {
    sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1
}

# Check if JSON contains a field with a specific value. Usage: echo "$JSON" | _hooker_json_match "field" "value"
_hooker_json_match() {
    grep -q "\"$1\"[[:space:]]*:[[:space:]]*\"*$2" 2>/dev/null
}

# JSON-escape stdin. No python3/perl dependency.
_hooker_json_escape() {
    awk '
    BEGIN { ORS=""; first=1 }
    {
        if (!first) printf "\\n"
        first=0
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        gsub(/\t/, "\\t")
        gsub(/\r/, "\\r")
        print
    }
    END { }
    ' | { IFS= read -r -d '' x || true; printf '"%s"' "$x"; }
}

# Portable sed-in-place. macOS sed requires '' after -i, GNU sed does not.
_hooker_sed_i() {
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "$@"
    else
        sed -i "$@"
    fi
}

# Reverse lines of a file. Portable replacement for tac.
_hooker_reverse() {
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}'
}

# Get last assistant turn from transcript. Filters noise (progress, hook_progress),
# stops at real user prompt (not tool_result).
# Real user prompts have "type":"user" WITHOUT "sourceToolAssistantUUID" on the same line.
# Usage: _hooker_last_turn "$TRANSCRIPT_PATH"
_hooker_last_turn() {
    local TRANSCRIPT="$1"
    [ -z "$TRANSCRIPT" ] || [ ! -f "$TRANSCRIPT" ] && return 1
    # Note: || true prevents SIGPIPE (141) when awk exits early and breaks the pipe.
    # Without it, set -o pipefail in callers treats SIGPIPE as failure.
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}' "$TRANSCRIPT" \
        | grep -v '"type":"progress"' | grep -v '"type":"hook_progress"' \
        | awk '/"type":"user"/ && !/sourceToolAssistantUUID/{exit} {print}' || true
}

# Strip <hidden> tags from a string, return visible part only.
# Handles both single-line (<hidden>...</hidden> on one line) and multiline.
_hooker_strip_hidden() {
    echo "$1" | sed 's/<hidden>[^<]*<\/hidden>//g' | awk '
    /<hidden>/ { skip=1; next }
    /<\/hidden>/ { skip=0; next }
    !skip { print }
    '
}

# JSON response helpers — all ALWAYS VISIBLE to user.
# <hidden> tags are stripped but content is NOT hidden.

warn() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"${HOOKER_EVENT}\", \"systemMessage\": ${ESCAPED}}}"
}

deny() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Denied by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"deny\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

allow() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Allowed by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"allow\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

ask() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Hooker requests confirmation}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"ask\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

block() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Blocked by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

remind() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

# Context injection helpers.
# inject() is the ONLY helper that hides content from user (via XML trick).

inject() {
    cat <<INJECT_EOF
</local-command-stdout>

$1

<local-command-stdout>
INJECT_EOF
}

visible() {
    echo "$1"
}

context() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"additionalContext\": ${ESCAPED}}"
}

# File loaders.
# Only useful inside inject() — JSON helpers (block, deny, etc.) are always visible.
# Looks in: .claude/hooker/ → ~/.claude/hooker/ → plugin templates/

load_md() {
    local FILE=""
    for DIR in ".claude/hooker" "${HOME}/.claude/hooker" "${CLAUDE_PLUGIN_ROOT:-}/templates"; do
        if [ -f "${DIR}/$1" ]; then
            FILE="${DIR}/$1"
            break
        fi
    done
    [ -z "$FILE" ] && return
    cat "$FILE"
}


# --- Recipe logic ---
# Directory Watchdog — warn about directories with too many files
# UserPromptSubmit hook: runs periodically on user messages
# WARN ONLY — never deletes. Use dir-cleanup for auto-removal.
RECIPE_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE=".claude/hooker/dir-watchdog.yml"

# Frequency control
FREQ=5
if [ -f "$CONFIG_FILE" ]; then
    F=$(sed -n 's/^check_frequency:[[:space:]]*\([0-9]*\)/\1/p' "$CONFIG_FILE" | head -1)
    [ -n "$F" ] && FREQ="$F"
fi
[ "$FREQ" -gt 1 ] 2>/dev/null && [ $((RANDOM % FREQ)) -ne 0 ] && exit 1

# Default threshold
THRESHOLD=30
if [ -f "$CONFIG_FILE" ]; then
    T=$(sed -n 's/^default_threshold:[[:space:]]*\([0-9]*\)/\1/p' "$CONFIG_FILE" | head -1)
    [ -n "$T" ] && THRESHOLD="$T"
fi

# Parse global ignore patterns
GLOBAL_IGNORE=""
if [ -f "$CONFIG_FILE" ]; then
    GLOBAL_IGNORE=$(sed -n 's/^ignore:[[:space:]]*\[//p' "$CONFIG_FILE" | sed 's/\].*//; s/,/ /g; s/[[:space:]]\+/ /g; s/^ //; s/ $//' | head -1)
fi

# Collect warnings to temp file (avoids subshell variable loss)
WARN_FILE=$(mktemp 2>/dev/null || echo "/tmp/hooker_dirwatch_$$")

# Check if filename matches any ignore pattern (supports * glob)
is_ignored() {
    local FNAME="$1" PATTERNS="$2"
    [ -z "$PATTERNS" ] && return 1
    for pat in $PATTERNS; do
        case "$FNAME" in
            $pat) return 0 ;;
        esac
    done
    return 1
}

# Count files in directory, excluding ignored
count_files() {
    local DIR="$1" EXTS="$2" IGNORE="$3"
    local COUNT=0
    local ALL_IGNORE="${GLOBAL_IGNORE} ${IGNORE}"

    find "$DIR" -maxdepth 1 -type f 2>/dev/null | while IFS= read -r fpath; do
        FNAME=$(basename "$fpath")
        is_ignored "$FNAME" "$ALL_IGNORE" && continue
        if [ -n "$EXTS" ]; then
            EXT=$(echo "$FNAME" | sed 's/.*\.//' | tr '[:upper:]' '[:lower:]')
            echo "$EXTS" | grep -qw "$EXT" || continue
        fi
        echo "$fpath"
    done | wc -l
}

# Check a directory, append warning to WARN_FILE
check_dir() {
    local DIR="$1" MAX="$2" EXTS="$3" IGNORE="$4"
    [ -d "$DIR" ] || return
    local COUNT
    COUNT=$(count_files "$DIR" "$EXTS" "$IGNORE")
    [ "$COUNT" -gt "$MAX" ] && echo "Directory \`${DIR}\` has ${COUNT} files (threshold: ${MAX})." >> "$WARN_FILE"
}

# Parse configured rules
CONFIGURED_PATHS=""
if [ -f "$CONFIG_FILE" ]; then
    CUR_PATH="" CUR_MAX="$THRESHOLD" CUR_EXT="" CUR_IGNORE=""
    while IFS= read -r line; do
        case "$line" in
            *"- path:"*)
                [ -n "$CUR_PATH" ] && check_dir "$CUR_PATH" "$CUR_MAX" "$CUR_EXT" "$CUR_IGNORE"
                CUR_PATH=$(echo "$line" | sed 's/.*path:[[:space:]]*//' | sed 's/[[:space:]]*$//; s|/$||')
                CUR_MAX="$THRESHOLD" CUR_EXT="" CUR_IGNORE=""
                CONFIGURED_PATHS="${CONFIGURED_PATHS}|${CUR_PATH}"
                ;;
            *"max_files:"*)
                CUR_MAX=$(echo "$line" | sed 's/.*max_files:[[:space:]]*//' | sed 's/[[:space:]]*$//')
                ;;
            *"extensions:"*)
                CUR_EXT=$(echo "$line" | sed 's/.*\[//; s/\].*//; s/,/ /g; s/[[:space:]]\+/ /g; s/^ //; s/ $//')
                ;;
            *"ignore:"*)
                CUR_IGNORE=$(echo "$line" | sed 's/.*\[//; s/\].*//; s/,/ /g; s/[[:space:]]\+/ /g; s/^ //; s/ $//')
                ;;
        esac
    done < "$CONFIG_FILE"
    [ -n "$CUR_PATH" ] && check_dir "$CUR_PATH" "$CUR_MAX" "$CUR_EXT" "$CUR_IGNORE"
fi

# Scan unconfigured directories
if [ "$THRESHOLD" -gt 0 ]; then
    find . -maxdepth 3 -type d \
        ! -path './.git/*' ! -path '*/node_modules/*' ! -path '*/__pycache__/*' \
        ! -path '*/vendor/*' ! -path '*/dist/*' ! -path '*/build/*' \
        ! -path '*/target/*' ! -path '*/.next/*' ! -path '*/.claude/*' \
        ! -name '.*' 2>/dev/null | while IFS= read -r dir; do
        REL=$(echo "$dir" | sed 's|^\./||')
        [ "$REL" = "." ] && continue
        echo "$CONFIGURED_PATHS" | grep -q "|${REL}" && continue
        COUNT=$(count_files "$dir" "" "")
        [ "$COUNT" -gt "$THRESHOLD" ] && echo "Directory \`${REL}\` has ${COUNT} files (threshold: ${THRESHOLD}). No rule in dir-watchdog.yml." >> "$WARN_FILE"
    done
fi

WARNINGS=$(cat "$WARN_FILE" 2>/dev/null)
rm -f "$WARN_FILE" 2>/dev/null

[ -z "$WARNINGS" ] && exit 1

# Add config hint if no config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    MSG_HINT=$(sed -n 's/^no_config_hint:[[:space:]]*"\(.*\)"/\1/p' "${RECIPE_DIR}/messages.yml")
    WARNINGS="${WARNINGS}
${MSG_HINT}"
fi

inject "$WARNINGS"
exit 0
