#!/bin/bash
# Hooker standalone execute.sh — compiled from match script + helpers
# Can be used directly in .claude/settings.json without hooker plugin.
# Generated by: cd src && go run .
# Hooker version: 0.25.1
#
# Exit code translation (standalone has no inject.sh to catch codes):
#   exit 0 → ok (pass through)
#   exit 1 → skip/no-match → translated to exit 0 (not an error)
#   exit 2+ → real error → translated to exit 1 (Claude Code shows "hook error")

INPUT=$(cat)
HOOKER_EVENT=$(echo "$INPUT" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_CWD=$(echo "$INPUT" | sed -n 's/.*"cwd"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
HOOKER_TRANSCRIPT=$(echo "$INPUT" | sed -n 's/.*"transcript_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
export HOOKER_EVENT HOOKER_CWD HOOKER_TRANSCRIPT

# --- Inlined helpers ---
# Hooker — helper functions for match scripts
# Source this in your match script: source "${HOOKER_HELPERS}"
# Then use: warn "message", deny "reason", allow, block "reason", etc.
#
# Cross-platform: works on Linux, macOS, and Windows (Git Bash).
# No dependencies on python3, perl, or tac.
#
# Visibility:
#   inject() — hidden from user by default (XML trick). Use <visible> tags to show parts.
#   JSON helpers (warn, deny, block, remind, allow, ask) — ALWAYS VISIBLE to user.
#     <hidden> tags are stripped but content is NOT hidden (Claude Code renders
#     JSON reason/message as plaintext — XML trick cannot escape JSON strings).
#   load_md "file.md" — only useful inside inject(), not inside JSON helpers.

# Extract a JSON string field value. Usage: echo "$JSON" | _hooker_json_field "field_name"
_hooker_json_field() {
    sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1
}

# Check if JSON contains a field with a specific value. Usage: echo "$JSON" | _hooker_json_match "field" "value"
_hooker_json_match() {
    grep -q "\"$1\"[[:space:]]*:[[:space:]]*\"*$2" 2>/dev/null
}

# JSON-escape stdin. No python3/perl dependency.
_hooker_json_escape() {
    awk '
    BEGIN { ORS=""; first=1 }
    {
        if (!first) printf "\\n"
        first=0
        gsub(/\\/, "\\\\")
        gsub(/"/, "\\\"")
        gsub(/\t/, "\\t")
        gsub(/\r/, "\\r")
        print
    }
    END { }
    ' | { IFS= read -r -d '' x || true; printf '"%s"' "$x"; }
}

# Portable sed-in-place. macOS sed requires '' after -i, GNU sed does not.
_hooker_sed_i() {
    if [ "$(uname)" = "Darwin" ]; then
        sed -i '' "$@"
    else
        sed -i "$@"
    fi
}

# Reverse lines of a file. Portable replacement for tac.
_hooker_reverse() {
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}'
}

# Get last assistant turn from transcript. Filters noise (progress, hook_progress),
# stops at real user prompt (not tool_result).
# Real user prompts have "type":"user" WITHOUT "sourceToolAssistantUUID" on the same line.
# Usage: _hooker_last_turn "$TRANSCRIPT_PATH"
_hooker_last_turn() {
    local TRANSCRIPT="$1"
    [ -z "$TRANSCRIPT" ] || [ ! -f "$TRANSCRIPT" ] && return 1
    # Note: || true prevents SIGPIPE (141) when awk exits early and breaks the pipe.
    # Without it, set -o pipefail in callers treats SIGPIPE as failure.
    awk '{a[NR]=$0} END{for(i=NR;i>=1;i--)print a[i]}' "$TRANSCRIPT" \
        | grep -v '"type":"progress"' | grep -v '"type":"hook_progress"' \
        | awk '/"type":"user"/ && !/sourceToolAssistantUUID/{exit} {print}' || true
}

# Strip <hidden> tags from a string, return visible part only.
# Handles both single-line (<hidden>...</hidden> on one line) and multiline.
_hooker_strip_hidden() {
    echo "$1" | sed 's/<hidden>[^<]*<\/hidden>//g' | awk '
    /<hidden>/ { skip=1; next }
    /<\/hidden>/ { skip=0; next }
    !skip { print }
    '
}

# JSON response helpers — all ALWAYS VISIBLE to user.
# <hidden> tags are stripped but content is NOT hidden.

warn() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"${HOOKER_EVENT}\", \"systemMessage\": ${ESCAPED}}}"
}

deny() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Denied by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"deny\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

allow() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Allowed by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"allow\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

ask() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Hooker requests confirmation}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"hookSpecificOutput\": {\"hookEventName\": \"PreToolUse\", \"permissionDecision\": \"ask\", \"permissionDecisionReason\": ${ESCAPED}}}"
}

block() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "${1:-Blocked by Hooker}")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

remind() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"decision\": \"block\", \"reason\": ${ESCAPED}}"
}

# Context injection helpers.
# inject() is the ONLY helper that hides content from user (via XML trick).

inject() {
    cat <<INJECT_EOF
</local-command-stdout>

$1

<local-command-stdout>
INJECT_EOF
}

visible() {
    echo "$1"
}

context() {
    local CLEAN
    CLEAN=$(_hooker_strip_hidden "$1")
    local ESCAPED
    ESCAPED=$(echo "$CLEAN" | _hooker_json_escape)
    echo "{\"additionalContext\": ${ESCAPED}}"
}

# File loaders.
# Only useful inside inject() — JSON helpers (block, deny, etc.) are always visible.
# Looks in: .claude/hooker/ → ~/.claude/hooker/ → plugin templates/

load_md() {
    local FILE=""
    for DIR in ".claude/hooker" "${HOME}/.claude/hooker" "${CLAUDE_PLUGIN_ROOT:-}/templates"; do
        if [ -f "${DIR}/$1" ]; then
            FILE="${DIR}/$1"
            break
        fi
    done
    [ -z "$FILE" ] && return
    cat "$FILE"
}


# --- Exit code translation ---
_hooker_main() {
# Directory Cleanup — auto-remove oldest files from bloated directories
# UserPromptSubmit hook: runs periodically on user messages
# DESTRUCTIVE — only acts on rules with action: cleanup in dir-watchdog.yml
# Respects global and per-rule ignore patterns.
RECIPE_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE=".claude/hooker/dir-watchdog.yml"

# Must have config — never auto-delete without explicit rules
[ -f "$CONFIG_FILE" ] || exit 1

# Frequency control
FREQ=5
F=$(sed -n 's/^check_frequency:[[:space:]]*\([0-9]*\)/\1/p' "$CONFIG_FILE" | head -1)
[ -n "$F" ] && FREQ="$F"
[ "$FREQ" -gt 1 ] 2>/dev/null && [ $((RANDOM % FREQ)) -ne 0 ] && exit 1

THRESHOLD=30
T=$(sed -n 's/^default_threshold:[[:space:]]*\([0-9]*\)/\1/p' "$CONFIG_FILE" | head -1)
[ -n "$T" ] && THRESHOLD="$T"

# Parse global ignore patterns
GLOBAL_IGNORE=""
GLOBAL_IGNORE=$(sed -n 's/^ignore:[[:space:]]*\[//p' "$CONFIG_FILE" | sed 's/\].*//; s/,/ /g; s/[[:space:]]\+/ /g; s/^ //; s/ $//' | head -1)

MSG_CLEANUP=$(sed -n 's/^cleanup_done:[[:space:]]*"\(.*\)"/\1/p' "${RECIPE_DIR}/messages.yml")

RESULT_FILE=$(mktemp 2>/dev/null || echo "/tmp/hooker_dirclean_$$")

# Check if filename matches any ignore pattern (supports * glob)
is_ignored() {
    local FNAME="$1" PATTERNS="$2"
    [ -z "$PATTERNS" ] && return 1
    for pat in $PATTERNS; do
        case "$FNAME" in
            $pat) return 0 ;;
        esac
    done
    return 1
}

# Parse rules — only process action: cleanup
CUR_PATH="" CUR_MAX="$THRESHOLD" CUR_EXT="" CUR_ACTION="" CUR_IGNORE=""
process_rule() {
    [ -z "$CUR_PATH" ] && return
    [ "$CUR_ACTION" != "cleanup" ] && return
    [ -d "$CUR_PATH" ] || return

    local ALL_IGNORE="${GLOBAL_IGNORE} ${CUR_IGNORE}"

    # List matching files with mtime, excluding ignored
    local FILES_LIST
    FILES_LIST=$(mktemp 2>/dev/null || echo "/tmp/hooker_flist_$$")

    find "$CUR_PATH" -maxdepth 1 -type f -printf '%T@ %p\n' 2>/dev/null | while IFS= read -r line; do
        FILE=$(echo "$line" | sed 's/^[^ ]* //')
        FNAME=$(basename "$FILE")

        # Check ignore
        is_ignored "$FNAME" "$ALL_IGNORE" && continue

        # Check extension filter
        if [ -n "$CUR_EXT" ]; then
            EXT=$(echo "$FNAME" | sed 's/.*\.//' | tr '[:upper:]' '[:lower:]')
            echo "$CUR_EXT" | grep -qw "$EXT" || continue
        fi

        echo "$line"
    done > "$FILES_LIST"

    local COUNT
    COUNT=$(wc -l < "$FILES_LIST")

    if [ "$COUNT" -gt "$CUR_MAX" ]; then
        local EXCESS=$((COUNT - CUR_MAX))
        local REMOVED=0
        sort -n "$FILES_LIST" | head -"$EXCESS" | while IFS= read -r line; do
            FILE=$(echo "$line" | sed 's/^[^ ]* //')
            rm -f "$FILE" 2>/dev/null
        done
        REMOVED=$EXCESS
        local KEPT=$((COUNT - REMOVED))
        local MSG=$(echo "$MSG_CLEANUP" | sed "s|{path}|$CUR_PATH|g; s|{removed}|$REMOVED|g; s|{kept}|$KEPT|g; s|{max}|$CUR_MAX|g")
        echo "$MSG" >> "$RESULT_FILE"
    fi

    rm -f "$FILES_LIST" 2>/dev/null
}

while IFS= read -r line; do
    case "$line" in
        *"- path:"*)
            process_rule
            CUR_PATH=$(echo "$line" | sed 's/.*path:[[:space:]]*//' | sed 's/[[:space:]]*$//; s|/$||')
            CUR_MAX="$THRESHOLD" CUR_EXT="" CUR_ACTION="" CUR_IGNORE=""
            ;;
        *"max_files:"*)
            CUR_MAX=$(echo "$line" | sed 's/.*max_files:[[:space:]]*//' | sed 's/[[:space:]]*$//')
            ;;
        *"extensions:"*)
            CUR_EXT=$(echo "$line" | sed 's/.*\[//; s/\].*//; s/,/ /g; s/[[:space:]]\+/ /g; s/^ //; s/ $//')
            ;;
        *"action:"*)
            CUR_ACTION=$(echo "$line" | sed 's/.*action:[[:space:]]*//' | sed 's/[[:space:]]*$//')
            ;;
        *"ignore:"*)
            # Only per-rule ignore if indented (inside a rule block)
            case "$line" in
                [[:space:]]*)
                    CUR_IGNORE=$(echo "$line" | sed 's/.*\[//; s/\].*//; s/,/ /g; s/[[:space:]]\+/ /g; s/^ //; s/ $//')
                    ;;
            esac
            ;;
    esac
done < "$CONFIG_FILE"
process_rule

RESULTS=$(cat "$RESULT_FILE" 2>/dev/null)
rm -f "$RESULT_FILE" 2>/dev/null

[ -z "$RESULTS" ] && exit 1

inject "$RESULTS"
exit 0
}
_hooker_main
_EXIT=$?
if [ "$_EXIT" -eq 0 ]; then exit 0
elif [ "$_EXIT" -eq 1 ]; then exit 0   # skip/no-match → not an error
else exit 1                             # exit 2+ → real error
fi
